# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ghazi/Downloads/master_work/BRAM_PRJ_/BRAM_PRJ.srcs/sources_1/ip/STORE_DISPARITY_IMAGE/STORE_DISPARITY_IMAGE.xci
# IP: The module: 'STORE_DISPARITY_IMAGE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ghazi/Downloads/master_work/BRAM_PRJ_/BRAM_PRJ.srcs/sources_1/ip/STORE_DISPARITY_IMAGE/STORE_DISPARITY_IMAGE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'STORE_DISPARITY_IMAGE'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ghazi/Downloads/master_work/BRAM_PRJ_/BRAM_PRJ.srcs/sources_1/ip/STORE_DISPARITY_IMAGE/STORE_DISPARITY_IMAGE.xci
# IP: The module: 'STORE_DISPARITY_IMAGE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ghazi/Downloads/master_work/BRAM_PRJ_/BRAM_PRJ.srcs/sources_1/ip/STORE_DISPARITY_IMAGE/STORE_DISPARITY_IMAGE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'STORE_DISPARITY_IMAGE'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
