######################################################################
#
# File name : TOP_tb_synchronized_simulate.do
# Created on: Tue Sep 13 15:57:35 CEST 2016
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -t 1ps -lib xil_defaultlib TOP_tb_synchronized_opt

do {TOP_tb_synchronized_wave.do}

view wave
view structure
view signals

do {TOP_tb_synchronized.udo}

run 15.2ms
