######################################################################
#
# File name : TOP_tb_synchronized_wave.do
# Created on: Tue Sep 13 15:57:35 CEST 2016
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
