######################################################################
#
# File name : TOP_tb_synchronized_elaborate.do
# Created on: Tue Sep 13 15:57:33 CEST 2016
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vopt -64 +acc -L unisims_ver -L secureip -L xil_defaultlib -work xil_defaultlib xil_defaultlib.TOP_tb_synchronized xil_defaultlib.glbl -o TOP_tb_synchronized_opt
