######################################################################
#
# File name : TOP_tb_synchronized.udo
# Created on: Tue Sep 13 12:35:49 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
