######################################################################
#
# File name : TOP_tb_synchronized_wave.do
# Created on: Tue Sep 13 12:35:49 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
