######################################################################
#
# File name : M1_M2_tb.udo
# Created on: Fri Jul 29 14:23:28 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
