######################################################################
#
# File name : M1_M2_tb_elaborate.do
# Created on: Fri Jul 29 14:23:25 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vopt -64 +acc -L unisims_ver -L secureip -L xil_defaultlib -work xil_defaultlib xil_defaultlib.M1_M2_tb xil_defaultlib.glbl -o M1_M2_tb_opt
