######################################################################
#
# File name : M1_M2_tb_simulate.do
# Created on: Fri Jul 29 14:23:28 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -t 1ps -lib xil_defaultlib M1_M2_tb_opt

do {M1_M2_tb_wave.do}

view wave
view structure
view signals

do {M1_M2_tb.udo}

run 1500ns
