######################################################################
#
# File name : READ_FILE_BRAM_TB.udo
# Created on: Sat Jun 25 12:59:47 CEST 2016
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
