######################################################################
#
# File name : M1_M2_tb.udo
# Created on: Tue Jul 26 20:46:32 CEST 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
