######################################################################
#
# File name : M1_M2_tb_select_points.udo
# Created on: Mon Aug 01 11:02:18 CEST 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
