######################################################################
#
# File name : tb_bram.udo
# Created on: Sat Jun 25 14:32:45 CEST 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
