# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/BUFFER_ROW/BUFFER_ROW.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BUFFER_ROW || ORIG_REF_NAME==BUFFER_ROW}]
